/**
 * Sample planogram data – mocked third-party API payloads
 * Planogram 1: prod_dd.json (Mixed Grocery & Personal Care)
 * Planogram 2: Beverages & Dairy Shelf
 */

import type { PlanogramPayload } from "@/types/planogram";

/** Planogram 1 – Mixed Grocery & Personal Care Shelf (from prod_dd.json) */
export const PLANOGRAM_POC_001: PlanogramPayload = {
  planogram: {
    id: "PLN-SHELF-POC-001",
    name: "Mixed Grocery & Personal Care Shelf",
    version: "1.0",
    createdDate: "2026-02-15",
    fixture: {
      type: "wall_shelving",
      width: 1200,
      height: 2000,
      depth: 400,
      units: "mm",
      shelfCount: 4,
      shelves: [
        {
          shelfNumber: 1,
          name: "Top Shelf - Aperitif & Bakery Snacks",
          verticalPosition: 1500,
          height: 350,
          products: [
            {
              sku: "IM-LC-ROQ",
              brand: "Intermarché",
              name: "Les Créations Mini Crêpes Roquefort",
              category: "Aperitif Snacks",
              xPosition: 0,
              facings: 3,
              depthCount: 2,
              width: 120,
              height: 180,
              depth: 80,
              optimalStock: 6,
              currentStock: 6,
            },
            {
              sku: "IM-LC-CHED",
              brand: "Intermarché",
              name: "Les Créations Mini Crêpes Cheddar",
              category: "Aperitif Snacks",
              xPosition: 360,
              facings: 3,
              depthCount: 2,
              width: 120,
              height: 180,
              depth: 80,
              optimalStock: 6,
              currentStock: 6,
            },
            {
              sku: "IM-LC-PESTO",
              brand: "Intermarché",
              name: "Les Créations Mini Crêpes Pesto",
              category: "Aperitif Snacks",
              xPosition: 720,
              facings: 3,
              depthCount: 2,
              width: 120,
              height: 180,
              depth: 80,
              optimalStock: 6,
              currentStock: 6,
            },
          ],
        },
        {
          shelfNumber: 2,
          name: "Second Shelf - Chips & Savory Snacks",
          verticalPosition: 1050,
          height: 350,
          products: [
            {
              sku: "CROKY-SNP",
              brand: "Croky",
              name: "à l'Ancienne Salt & Pepper Chips 200g",
              category: "Chips",
              xPosition: 0,
              facings: 3,
              depthCount: 2,
              width: 180,
              height: 280,
              depth: 120,
              optimalStock: 6,
              currentStock: 6,
            },
            {
              sku: "LORENZ-CURLY",
              brand: "Lorenz",
              name: "Curly Peanut Classic",
              category: "Snacks",
              xPosition: 540,
              facings: 3,
              depthCount: 2,
              width: 180,
              height: 260,
              depth: 120,
              optimalStock: 6,
              currentStock: 6,
            },
            {
              sku: "PRING-SV",
              brand: "Pringles",
              name: "Salt & Vinegar",
              category: "Chips",
              xPosition: 900,
              facings: 2,
              depthCount: 2,
              width: 80,
              height: 240,
              depth: 80,
              optimalStock: 4,
              currentStock: 4,
            },
          ],
        },
        {
          shelfNumber: 3,
          name: "Third Shelf - Kids Food & Coffee",
          verticalPosition: 600,
          height: 350,
          products: [
            {
              sku: "OLV-CRUNCHY",
              brand: "Olvarit",
              name: "Little Wonders Crunchy Stars Cacao",
              category: "Kids Cereal",
              xPosition: 0,
              facings: 2,
              depthCount: 2,
              width: 140,
              height: 220,
              depth: 90,
              optimalStock: 4,
              currentStock: 4,
            },
            {
              sku: "OLV-MUESLI",
              brand: "Olvarit",
              name: "Little Wonders Mini Muesli Mixed Cereal & Fruit",
              category: "Kids Cereal",
              xPosition: 280,
              facings: 2,
              depthCount: 2,
              width: 140,
              height: 220,
              depth: 90,
              optimalStock: 4,
              currentStock: 4,
            },
            {
              sku: "LAV-CREMA",
              brand: "Lavazza",
              name: "Crema e Gusto Classico Ground Coffee 250g",
              category: "Coffee",
              xPosition: 560,
              facings: 3,
              depthCount: 2,
              width: 120,
              height: 200,
              depth: 70,
              optimalStock: 6,
              currentStock: 6,
            },
          ],
        },
        {
          shelfNumber: 4,
          name: "Bottom Shelf - Personal Care & Grooming",
          verticalPosition: 0,
          height: 350,
          products: [
            {
              sku: "POM-GEL",
              brand: "Pommette Bio",
              name: "Gel Lavant",
              category: "Baby Care",
              xPosition: 0,
              facings: 2,
              depthCount: 2,
              width: 90,
              height: 220,
              depth: 70,
              optimalStock: 4,
              currentStock: 4,
            },
            {
              sku: "POM-EAU",
              brand: "Pommette Bio",
              name: "Eau Nettoyante",
              category: "Baby Care",
              xPosition: 200,
              facings: 2,
              depthCount: 2,
              width: 90,
              height: 220,
              depth: 70,
              optimalStock: 4,
              currentStock: 4,
            },
            {
              sku: "LAB-PANS",
              brand: "Labell",
              name: "20 Pansements Kids",
              category: "First Aid",
              xPosition: 400,
              facings: 2,
              depthCount: 2,
              width: 80,
              height: 140,
              depth: 40,
              optimalStock: 4,
              currentStock: 4,
            },
            {
              sku: "LAB-RAZOR",
              brand: "Labell Men",
              name: "System 3 Blades Razor",
              category: "Grooming",
              xPosition: 600,
              facings: 2,
              depthCount: 2,
              width: 100,
              height: 200,
              depth: 40,
              optimalStock: 4,
              currentStock: 4,
            },
            {
              sku: "LAB-REFILL",
              brand: "Labell Men",
              name: "System 3 Blades Refill x4",
              category: "Grooming",
              xPosition: 820,
              facings: 2,
              depthCount: 2,
              width: 100,
              height: 160,
              depth: 40,
              optimalStock: 4,
              currentStock: 4,
            },
          ],
        },
      ],
    },
  },
  stockingRules: {
    highDemandProducts: ["PRING-SV", "LAV-CREMA"],
    restockThreshold: 0.3,
    notes: "Restock when inventory falls below 30% of optimal level",
  },
  metadata: {
    location: "POC Demo Store",
    lastUpdated: "2026-02-15",
    status: "active",
    totalSKUs: 13,
    totalProducts: 64,
  },
};

/** Planogram 2 – Beverages & Dairy Shelf (generated, same structure) */
export const PLANOGRAM_POC_002: PlanogramPayload = {
  planogram: {
    id: "PLN-SHELF-POC-002",
    name: "Beverages & Dairy Shelf",
    version: "1.0",
    createdDate: "2026-02-15",
    fixture: {
      type: "wall_shelving",
      width: 1200,
      height: 2000,
      depth: 400,
      units: "mm",
      shelfCount: 4,
      shelves: [
        {
          shelfNumber: 1,
          name: "Top Shelf - Water & Sparkling",
          verticalPosition: 1500,
          height: 350,
          products: [
            {
              sku: "EVIAN-1.5",
              brand: "Evian",
              name: "Natural Spring Water 1.5L",
              category: "Water",
              xPosition: 0,
              facings: 4,
              depthCount: 2,
              width: 100,
              height: 320,
              depth: 100,
              optimalStock: 8,
              currentStock: 8,
            },
            {
              sku: "PERRIER-750",
              brand: "Perrier",
              name: "Sparkling Mineral Water 750ml",
              category: "Sparkling Water",
              xPosition: 400,
              facings: 3,
              depthCount: 2,
              width: 80,
              height: 260,
              depth: 80,
              optimalStock: 6,
              currentStock: 6,
            },
            {
              sku: "VITTEL-500",
              brand: "Vittel",
              name: "Still Water 500ml",
              category: "Water",
              xPosition: 640,
              facings: 4,
              depthCount: 2,
              width: 70,
              height: 220,
              depth: 70,
              optimalStock: 8,
              currentStock: 8,
            },
          ],
        },
        {
          shelfNumber: 2,
          name: "Second Shelf - Soft Drinks",
          verticalPosition: 1050,
          height: 350,
          products: [
            {
              sku: "COCA-500",
              brand: "Coca-Cola",
              name: "Classic 500ml",
              category: "Soft Drinks",
              xPosition: 0,
              facings: 4,
              depthCount: 2,
              width: 70,
              height: 220,
              depth: 70,
              optimalStock: 8,
              currentStock: 8,
            },
            {
              sku: "ORAN-330",
              brand: "Orangina",
              name: "Original 330ml",
              category: "Soft Drinks",
              xPosition: 280,
              facings: 3,
              depthCount: 2,
              width: 65,
              height: 200,
              depth: 65,
              optimalStock: 6,
              currentStock: 6,
            },
            {
              sku: "SCHWEPPES-TONIC",
              brand: "Schweppes",
              name: "Indian Tonic Water 1L",
              category: "Soft Drinks",
              xPosition: 475,
              facings: 2,
              depthCount: 2,
              width: 90,
              height: 280,
              depth: 90,
              optimalStock: 4,
              currentStock: 4,
            },
          ],
        },
        {
          shelfNumber: 3,
          name: "Third Shelf - Juices & Nectars",
          verticalPosition: 600,
          height: 350,
          products: [
            {
              sku: "TROP-ORANGE",
              brand: "Tropicana",
              name: "Pure Premium Orange 1L",
              category: "Juices",
              xPosition: 0,
              facings: 3,
              depthCount: 2,
              width: 90,
              height: 260,
              depth: 90,
              optimalStock: 6,
              currentStock: 6,
            },
            {
              sku: "INNOCENT-APPLE",
              brand: "Innocent",
              name: "Apple Juice 1L",
              category: "Juices",
              xPosition: 270,
              facings: 3,
              depthCount: 2,
              width: 90,
              height: 260,
              depth: 90,
              optimalStock: 6,
              currentStock: 6,
            },
            {
              sku: "JAF-APRICOT",
              brand: "Jaf",
              name: "Apricot Nectar 1L",
              category: "Nectars",
              xPosition: 540,
              facings: 2,
              depthCount: 2,
              width: 90,
              height: 260,
              depth: 90,
              optimalStock: 4,
              currentStock: 4,
            },
          ],
        },
        {
          shelfNumber: 4,
          name: "Bottom Shelf - Dairy & Milk",
          verticalPosition: 0,
          height: 350,
          products: [
            {
              sku: "DANONE-NAT",
              brand: "Danone",
              name: "Natural Yogurt 4x125g",
              category: "Dairy",
              xPosition: 0,
              facings: 3,
              depthCount: 2,
              width: 120,
              height: 180,
              depth: 120,
              optimalStock: 6,
              currentStock: 6,
            },
            {
              sku: "ACTIVIA-VAN",
              brand: "Activia",
              name: "Vanilla Yogurt 4x125g",
              category: "Dairy",
              xPosition: 360,
              facings: 3,
              depthCount: 2,
              width: 120,
              height: 180,
              depth: 120,
              optimalStock: 6,
              currentStock: 6,
            },
            {
              sku: "LACTEL-SEMI",
              brand: "Lactel",
              name: "Semi-Skimmed Milk 1L",
              category: "Milk",
              xPosition: 720,
              facings: 4,
              depthCount: 2,
              width: 80,
              height: 260,
              depth: 80,
              optimalStock: 8,
              currentStock: 8,
            },
          ],
        },
      ],
    },
  },
  stockingRules: {
    highDemandProducts: ["COCA-500", "TROP-ORANGE"],
    restockThreshold: 0.3,
    notes: "Restock when inventory falls below 30% of optimal level",
  },
  metadata: {
    location: "POC Demo Store",
    lastUpdated: "2026-02-15",
    status: "active",
    totalSKUs: 12,
    totalProducts: 72,
  },
};
