import type { PlanogramPayload } from "@/types/planogram";

export const PLANOGRAM_POC_001: PlanogramPayload = {
  name: "Mixed Grocery & Personal Care Shelf",
  description: "POC Demo Store",
  version: "1.0",
  status: "ACTIVE",
  fixture: {
    width: 1200,
    height: 2000,
    depth: 400,
  },
  shelves: [
    {
      id: "SHELF-001",
      y_position: 1500,
      height: 350,
      width: 1200,
      products: [
        {
          sku: "IM-LC-ROQ",
          name: "Les Creations Mini Crepes Roquefort",
          brand: "Intermarche",
          category: "Aperitif Snacks",
          size: { width: 120, height: 180, depth: 80 },
          x_position: 0,
          facings: 3,
          depth_count: 2,
          price: 4.99,
          velocity: 2,
          expiry_sensitive: true,
        },
        {
          sku: "IM-LC-CHED",
          name: "Les Creations Mini Crepes Cheddar",
          brand: "Intermarche",
          category: "Aperitif Snacks",
          size: { width: 120, height: 180, depth: 80 },
          x_position: 360,
          facings: 3,
          depth_count: 2,
          price: 4.99,
          velocity: 2,
          expiry_sensitive: true,
        },
        {
          sku: "IM-LC-PESTO",
          name: "Les Creations Mini Crepes Pesto",
          brand: "Intermarche",
          category: "Aperitif Snacks",
          size: { width: 120, height: 180, depth: 80 },
          x_position: 720,
          facings: 3,
          depth_count: 2,
          price: 4.99,
          velocity: 1,
          expiry_sensitive: true,
        },
      ],
    },
    {
      id: "SHELF-002",
      y_position: 1050,
      height: 350,
      width: 1200,
      products: [
        {
          sku: "CROKY-SNP",
          name: "Salt and Pepper Chips 200g",
          brand: "Croky",
          category: "Chips",
          size: { width: 180, height: 280, depth: 120 },
          x_position: 0,
          facings: 3,
          depth_count: 2,
          velocity: 3,
          expiry_sensitive: true,
        },
        {
          sku: "LORENZ-CURLY",
          name: "Curly Peanut Classic",
          brand: "Lorenz",
          category: "Snacks",
          size: { width: 180, height: 260, depth: 120 },
          x_position: 540,
          facings: 3,
          depth_count: 2,
          velocity: 2,
          expiry_sensitive: true,
        },
        {
          sku: "PRING-SV",
          name: "Salt and Vinegar",
          brand: "Pringles",
          category: "Chips",
          size: { width: 80, height: 240, depth: 80 },
          x_position: 900,
          facings: 2,
          depth_count: 2,
          velocity: 4,
          expiry_sensitive: true,
        },
      ],
    },
  ],
};

export const PLANOGRAM_POC_002: PlanogramPayload = {
  name: "Beverages and Dairy Shelf",
  description: "Cold drinks bay",
  version: "1.2",
  status: "DRAFT",
  fixture: {
    width: 1400,
    height: 2200,
    depth: 500,
  },
  shelves: [
    {
      id: "BEV-TOP",
      y_position: 1450,
      height: 320,
      width: 1400,
      products: [
        {
          sku: "WATER-STILL-500",
          barcode: "123456789001",
          name: "Still Water 500ml",
          brand: "Blue Spring",
          category: "Water",
          size: { width: 60, height: 210, depth: 60 },
          x_position: 0,
          facings: 6,
          depth_count: 3,
          price: 0.99,
          velocity: 8,
          expiry_sensitive: false,
        },
        {
          sku: "WATER-SPARK-500",
          barcode: "123456789002",
          name: "Sparkling Water 500ml",
          brand: "Blue Spring",
          category: "Sparkling Water",
          size: { width: 60, height: 210, depth: 60 },
          x_position: 360,
          facings: 6,
          depth_count: 3,
          price: 1.09,
          velocity: 6,
          expiry_sensitive: false,
        },
      ],
    },
    {
      id: "BEV-MID",
      y_position: 980,
      height: 340,
      width: 1400,
      products: [
        {
          sku: "COLA-330",
          barcode: "123456789003",
          name: "Cola 330ml",
          brand: "Fizz",
          category: "Soft Drinks",
          size: { width: 55, height: 150, depth: 55 },
          x_position: 0,
          facings: 8,
          depth_count: 3,
          price: 1.49,
          velocity: 9,
          expiry_sensitive: false,
        },
        {
          sku: "ORANGE-1L",
          barcode: "123456789004",
          name: "Orange Juice 1L",
          brand: "Sunfield",
          category: "Juices",
          size: { width: 75, height: 240, depth: 70 },
          x_position: 440,
          facings: 5,
          depth_count: 2,
          price: 2.49,
          velocity: 5,
          expiry_sensitive: true,
        },
      ],
    },
    {
      id: "BEV-LOW",
      y_position: 470,
      height: 360,
      width: 1400,
      products: [
        {
          sku: "MILK-WHOLE-1L",
          barcode: "123456789005",
          name: "Whole Milk 1L",
          brand: "Farm Fresh",
          category: "Milk",
          size: { width: 70, height: 235, depth: 70 },
          x_position: 0,
          facings: 6,
          depth_count: 2,
          price: 1.89,
          velocity: 7,
          expiry_sensitive: true,
        },
        {
          sku: "YOG-DRINK",
          barcode: "123456789006",
          name: "Drinkable Yogurt",
          brand: "Farm Fresh",
          category: "Dairy",
          size: { width: 65, height: 180, depth: 65 },
          x_position: 420,
          facings: 6,
          depth_count: 2,
          price: 1.29,
          velocity: 4,
          expiry_sensitive: true,
        },
      ],
    },
  ],
};
