import {
  ArrowLeft,
  ChevronLeft,
  ChevronRight,
  Edit3,
  Layers3,
  LayoutPanelLeft,
  Maximize,
  Plus,
  ShieldCheck,
  Trash2,
} from "lucide-react";
import { useState, type Dispatch, type SetStateAction } from "react";

import { ShelfTemplateModal, type ShelfTemplateModalValues } from "@/components/common/shelf-template-modal";
import {
  StoreFixtureModal,
  type StoreFixtureModalValues,
} from "@/components/common/store-fixture-modal";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { IconButton } from "@/components/ui/icon-button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import type { StoreDimensionUnit } from "@/lib/constants/dimensions";
import type {
  ComplianceRuleCategory,
  ComplianceRuleSetStatus,
  CreateComplianceRuleSetInput,
} from "@/queries/maker/api/compliance-rule-sets";
import { StoreOnboardingConfigNavItem } from "./store-onboarding-config-nav-item";
import { StoreOnboardingDimensionSection } from "./store-onboarding-dimension-section";

export type ConfigSection = "fixtures" | "shelfTemplates" | "rules" | "dimensions";

export type FixtureConfig = {
  id?: string;
  store_id?: string;
  type: string;
  /** Optional store-defined unique fixture identifier (generated by backend if omitted). */
  code?: string;
  width: string;
  height: string;
  depth: string;
  dimension_unit: StoreDimensionUnit;
  section: string;
  aisle: string;
  zone: string;
};

export type ShelfTemplateConfig = {
  name: string;
  description: string;
  fixtureType: string;
  zone: string;
  section: string;
  width: string;
  height: string;
  depth: string;
};

interface StoreOnboardingConfigStepProps {
  activeConfigSection: ConfigSection;
  setActiveConfigSection: Dispatch<SetStateAction<ConfigSection>>;
  configVisited: Record<ConfigSection, boolean>;
  setConfigVisited: Dispatch<SetStateAction<Record<ConfigSection, boolean>>>;
  fixtureTypes: FixtureConfig[];
  setFixtureTypes: Dispatch<SetStateAction<FixtureConfig[]>>;
  shelfTemplatesConfig: ShelfTemplateConfig[];
  setShelfTemplatesConfig: Dispatch<SetStateAction<ShelfTemplateConfig[]>>;
  newTemplate: ShelfTemplateConfig;
  setNewTemplate: Dispatch<SetStateAction<ShelfTemplateConfig>>;
  editingTemplateIndex: number | null;
  setEditingTemplateIndex: Dispatch<SetStateAction<number | null>>;
  showAddTemplateForm: boolean;
  setShowAddTemplateForm: Dispatch<SetStateAction<boolean>>;
  saveShelfTemplateFromModal: (values: ShelfTemplateModalValues) => void;
  dimensionUnits: string[];
  configForm: { default_dimensions: StoreDimensionUnit };
  setConfigForm: Dispatch<SetStateAction<{ default_dimensions: StoreDimensionUnit }>>;
  canContinueConfig: boolean;
  defaultComplianceRuleSet: CreateComplianceRuleSetInput;
  onUpdateDefaultComplianceRuleSet: (
    updater:
      | CreateComplianceRuleSetInput
      | ((current: CreateComplianceRuleSetInput) => CreateComplianceRuleSetInput),
  ) => void;
  shelfFixtureLabels: string[];
  onBack: () => void;
  isCreatingStore: boolean;
  onCreateStore: () => void | Promise<void>;
}

export function StoreOnboardingConfigStep({
  activeConfigSection,
  setActiveConfigSection,
  configVisited,
  setConfigVisited,
  fixtureTypes,
  setFixtureTypes,
  shelfTemplatesConfig,
  setShelfTemplatesConfig,
  newTemplate,
  setNewTemplate,
  editingTemplateIndex,
  setEditingTemplateIndex,
  showAddTemplateForm,
  setShowAddTemplateForm,
  saveShelfTemplateFromModal,
  dimensionUnits,
  configForm,
  setConfigForm,
  canContinueConfig,
  defaultComplianceRuleSet,
  onUpdateDefaultComplianceRuleSet,
  shelfFixtureLabels,
  onBack,
  isCreatingStore,
  onCreateStore,
}: StoreOnboardingConfigStepProps) {
  const { toast } = useToast();
  const [fixtureModalOpen, setFixtureModalOpen] = useState(false);
  const [editingFixtureIndex, setEditingFixtureIndex] = useState<number | null>(null);
  const [fixtureModalInitialValues, setFixtureModalInitialValues] = useState<
    Partial<StoreFixtureModalValues>
  >({});

  const configOrder: ConfigSection[] = ["fixtures", "shelfTemplates", "rules", "dimensions"];
  const currentConfigIndex = configOrder.indexOf(activeConfigSection);
  const isFirstConfigSection = currentConfigIndex <= 0;
  const isLastConfigSection = currentConfigIndex === configOrder.length - 1;
  const previousConfigSection = isFirstConfigSection
    ? undefined
    : configOrder[currentConfigIndex - 1];
  const nextConfigSection = isLastConfigSection ? undefined : configOrder[currentConfigIndex + 1];
  const configSectionLabel: Record<ConfigSection, string> = {
    fixtures: "Fixture Types",
    shelfTemplates: "Shelf Templates",
    rules: "Compliance Rules",
    dimensions: "Dimension Units",
  };
  const isConfigComplete = canContinueConfig && Object.values(configVisited).every(Boolean);
  const shouldShowCreateStore = isLastConfigSection && isConfigComplete;
  const complianceStatusOptions: ComplianceRuleSetStatus[] = ["DRAFT", "ACTIVE", "RETIRED"];
  const complianceRuleCategoryOptions: ComplianceRuleCategory[] = [
    "VISUAL",
    "SAFETY",
    "PROFITABILITY",
    "EFFICIENCY",
  ];
  const fallbackRule = {
    name: "",
    description: "",
    category: "VISUAL" as ComplianceRuleCategory,
    threshold: 95,
    is_active: true,
  };

  const updateRuleAtIndex = (
    ruleIndex: number,
    updates: Partial<CreateComplianceRuleSetInput["rules"][number]>,
  ) => {
    onUpdateDefaultComplianceRuleSet((current) => {
      const baseRules = current.rules.length > 0 ? current.rules : [fallbackRule];
      return {
        ...current,
        rules: baseRules.map((rule, idx) =>
          idx === ruleIndex ? { ...rule, ...updates } : rule,
        ),
      };
    });
  };

  const removeRuleAtIndex = (ruleIndex: number) => {
    onUpdateDefaultComplianceRuleSet((current) => {
      const nextRules = current.rules.filter((_, idx) => idx !== ruleIndex);
      return {
        ...current,
        rules: nextRules.length > 0 ? nextRules : [fallbackRule],
      };
    });
  };

  const openCreateFixture = () => {
    setEditingFixtureIndex(null);
    setFixtureModalInitialValues({
      dimensionUnit: configForm.default_dimensions,
    });
    setFixtureModalOpen(true);
  };

  const openEditFixture = (fixture: FixtureConfig, idx: number) => {
    setEditingFixtureIndex(idx);
    setFixtureModalInitialValues({
      type: fixture.type,
      code: fixture.code,
      width: fixture.width,
      height: fixture.height,
      depth: fixture.depth,
      dimensionUnit: fixture.dimension_unit,
      section: fixture.section,
      aisle: fixture.aisle,
      zone: fixture.zone,
    });
    setFixtureModalOpen(true);
  };

  const saveFixtureFromModal = (values: StoreFixtureModalValues) => {
    const type = values.type.trim();
    if (!type) return;

    const entry: FixtureConfig = {
      type,
      code: values.code?.trim() || undefined,
      width: values.width.trim() || "120",
      height: values.height.trim() || "200",
      depth: values.depth.trim() || "45",
      dimension_unit: values.dimensionUnit,
      section: values.section.trim() || "General",
      aisle: values.aisle.trim() || "A1",
      zone: values.zone.trim() || "General",
    };

    if (editingFixtureIndex !== null) {
      setFixtureTypes((prev) =>
        prev.map((item, idx) => {
          if (idx !== editingFixtureIndex) return item;
          return {
            ...item,
            ...entry,
          };
        }),
      );
    } else {
      setFixtureTypes((prev) => [...prev, entry]);
    }

    setEditingFixtureIndex(null);
    setFixtureModalOpen(false);
  };

  return (
    <Card noBorder className="bg-card/70 shadow-xl glassmorphism min-h-[70vh] lg:min-h-[72vh] flex flex-col">
      <CardHeader>
        <CardTitle>Store configuration</CardTitle>
        <CardDescription>
          Review the default setup this store will use for fixtures, shelves, compliance rules, and
          measurement units.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4 flex-1 flex flex-col min-h-0">
        <div className="flex flex-col-reverse gap-2 sm:flex-row sm:items-center sm:justify-between">
          <Button
            type="button"
            variant="outline"
            className="w-full sm:w-auto"
            onClick={() => {
              if (previousConfigSection) {
                setActiveConfigSection(previousConfigSection);
                setConfigVisited((prev) => ({ ...prev, [previousConfigSection]: true }));
                return;
              }
              onBack();
            }}
          >
            {previousConfigSection ? (
              <>
                <ChevronLeft className="size-4" />
                Back
              </>
            ) : (
              <>
                <ArrowLeft className="size-4" />
                Previous
              </>
            )}
          </Button>
          <Button
            variant="outline"
            type="button"
            className="w-full min-w-[160px] sm:w-auto"
            disabled={!canContinueConfig || (shouldShowCreateStore && isCreatingStore)}
            onClick={() => {
              if (!canContinueConfig) return;
              if (shouldShowCreateStore) {
                void onCreateStore();
                return;
              }
              if (!nextConfigSection) {
                const firstUnvisited = configOrder.find((section) => !configVisited[section]);
                if (firstUnvisited) {
                  setActiveConfigSection(firstUnvisited);
                  setConfigVisited((prev) => ({ ...prev, [firstUnvisited]: true }));
                  toast({
                    title: "Complete remaining configuration",
                    description: `Please review ${configSectionLabel[firstUnvisited]} before creating the store.`,
                    variant: "warning",
                  });
                }
                return;
              }
              setActiveConfigSection(nextConfigSection);
              setConfigVisited((prev) => ({ ...prev, [nextConfigSection]: true }));
            }}
          >
            {shouldShowCreateStore ? (
              isCreatingStore ? (
                "Creating..."
              ) : (
                "Create store"
              )
            ) : (
              <>
                Continue
                <ChevronRight className="size-4" />
              </>
            )}
          </Button>
        </div>

        <div className="flex flex-col gap-4 lg:flex-row flex-1 min-h-0">
          <div className="w-full lg:w-64 rounded-xl bg-background/40 p-3 space-y-2 lg:self-stretch">
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-1">
              Review configuration
            </p>
            <StoreOnboardingConfigNavItem
              icon={LayoutPanelLeft}
              label="Fixture Types"
              description="Core store fixtures"
              isActive={activeConfigSection === "fixtures"}
              isCompleted={configVisited.fixtures}
              onClick={() => {
                setActiveConfigSection("fixtures");
                setConfigVisited((prev) => ({ ...prev, fixtures: true }));
              }}
            />
            <StoreOnboardingConfigNavItem
              icon={Layers3}
              label="Shelf Templates"
              description="Standard shelf layouts"
              isActive={activeConfigSection === "shelfTemplates"}
              isCompleted={configVisited.shelfTemplates}
              onClick={() => {
                setActiveConfigSection("shelfTemplates");
                setConfigVisited((prev) => ({ ...prev, shelfTemplates: true }));
              }}
            />
            <StoreOnboardingConfigNavItem
              icon={ShieldCheck}
              label="Compliance Rules"
              description="Baseline checks"
              isActive={activeConfigSection === "rules"}
              isCompleted={configVisited.rules}
              onClick={() => {
                setActiveConfigSection("rules");
                setConfigVisited((prev) => ({ ...prev, rules: true }));
              }}
            />
            <StoreOnboardingConfigNavItem
              icon={Maximize}
              label="Dimension Units"
              description="Measurement defaults"
              isActive={activeConfigSection === "dimensions"}
              isCompleted={configVisited.dimensions}
              onClick={() => {
                setActiveConfigSection("dimensions");
                setConfigVisited((prev) => ({ ...prev, dimensions: true }));
              }}
            />
          </div>

          <div className="flex-1 min-h-0 space-y-4">
            {activeConfigSection === "fixtures" && (
              <section className="rounded-xl bg-background/40 p-4 space-y-4 h-full flex flex-col min-h-0">
                <div className="flex items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <LayoutPanelLeft className="size-4 text-accent" />
                    <div>
                      <h3 className="text-sm font-semibold text-foreground">Fixture Types</h3>
                    </div>
                  </div>
                  <Button
                    type="button"
                    size="sm"
                    variant="success"
                    className="h-8 gap-1.5"
                    onClick={openCreateFixture}
                  >
                    <Plus className="size-3.5" />
                    Add fixture
                  </Button>
                </div>
                <div className="flex-1 min-h-0 overflow-y-auto pr-1">
                  <div className="space-y-1.5 text-sm text-foreground">
                    {fixtureTypes.map((item, idx) => (
                      <div
                        key={`${item.type}-${idx}`}
                        className="flex items-center justify-between rounded-lg border border-border/60 bg-background/40 px-3 py-2"
                      >
                        <div>
                          <p className="font-medium">
                            {item.code ? `${item.type} - ${item.code}` : item.type}
                          </p>
                          <p className="text-xs text-muted-foreground">
                            {item.width}x{item.height}x{item.depth} {item.dimension_unit}
                          </p>
                          <p className="text-xs text-muted-foreground">
                            Section: {item.section} · Aisle: {item.aisle} · Zone: {item.zone}
                          </p>
                          {item.id && item.store_id && (
                            <p className="text-[10px] text-muted-foreground">
                              id: {item.id} · store_id: {item.store_id}
                            </p>
                          )}
                        </div>
                        <div className="flex items-center gap-1">
                          <IconButton
                            variant="icon-ghost"
                            size="icon-sm"
                            icon={<Edit3 className="size-4" />}
                            tooltip="Edit fixture"
                            onClick={() => openEditFixture(item, idx)}
                            aria-label={`Edit ${item.type}`}
                          />
                          <IconButton
                            variant="destructive-ghost"
                            size="icon-sm"
                            icon={<Trash2 className="size-4" />}
                            tooltip="Delete fixture"
                            onClick={() =>
                              setFixtureTypes((prev) => prev.filter((_, i) => i !== idx))
                            }
                            aria-label={`Delete ${item.type}`}
                          />
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </section>
            )}

            {activeConfigSection === "shelfTemplates" && (
              <section className="rounded-xl bg-background/40 p-4 space-y-4 h-full flex flex-col min-h-0">
                <div className="flex items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <Layers3 className="size-4 text-accent" />
                    <h3 className="text-sm font-semibold text-foreground">Shelf Templates</h3>
                  </div>
                  <Button
                    type="button"
                    size="sm"
                    variant="success"
                    className="h-8 gap-1.5"
                    onClick={() => {
                      setEditingTemplateIndex(null);
                      setShowAddTemplateForm(true);
                    }}
                  >
                    <Plus className="size-3.5" />
                    Add template
                  </Button>
                </div>
                <div className="flex-1 min-h-0 overflow-y-auto pr-1">
                  <div className="grid gap-3 sm:grid-cols-2">
                    {shelfTemplatesConfig.map((tpl, idx) => (
                      <div
                        key={`${tpl.name}-${idx}`}
                        className="rounded-xl border border-border/60 bg-background/40 p-4 space-y-2"
                      >
                        <div className="flex items-start justify-between gap-2">
                          <div className="min-w-0">
                            <p className="truncate font-semibold text-foreground">{tpl.name}</p>
                            <p className="mt-0.5 text-xs text-muted-foreground line-clamp-2">
                              {tpl.description}
                            </p>
                          </div>
                          <div className="flex items-center gap-1">
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => {
                                setEditingTemplateIndex(idx);
                                setNewTemplate(tpl);
                                setShowAddTemplateForm(true);
                              }}
                              aria-label={`Edit ${tpl.name}`}
                            >
                              <Edit3 className="size-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="text-destructive hover:text-destructive"
                              onClick={() =>
                                setShelfTemplatesConfig((prev) => prev.filter((_, i) => i !== idx))
                              }
                              aria-label={`Delete ${tpl.name}`}
                            >
                              <Trash2 className="size-4" />
                            </Button>
                          </div>
                        </div>
                        <div className="grid gap-1 text-xs">
                          <div className="flex justify-between">
                            <span className="text-muted-foreground">Fixture</span>
                            <span className="text-foreground font-medium">
                              {tpl.fixtureType.replace(/_/g, " ")}
                            </span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-muted-foreground">Dimensions</span>
                            <span className="text-foreground font-medium">
                              {tpl.width}×{tpl.height}×{tpl.depth}
                            </span>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </section>
            )}

            {activeConfigSection === "rules" && (
              <section className="rounded-xl bg-background/40 p-4 space-y-4 h-full flex flex-col min-h-0">
                <div className="flex items-center gap-2">
                  <ShieldCheck className="size-4 text-accent" />
                  <h3 className="text-sm font-semibold text-foreground">Compliance Rules</h3>
                </div>
                <p className="text-xs text-muted-foreground">
                  Configure the default compliance rules for this store.
                </p>
                <div className="flex-1 min-h-0 overflow-y-auto pr-1">
                  <div className="space-y-5">
                    <div className="grid gap-2">
                      <Label htmlFor="default-rule-set-name">Name</Label>
                      <Input
                        id="default-rule-set-name"
                        value={defaultComplianceRuleSet.name}
                        disabled
                        readOnly
                      />
                    </div>

                    <div className="grid gap-2">
                      <Label htmlFor="default-rule-set-status">Status</Label>
                      <Select
                        id="default-rule-set-status"
                        value={defaultComplianceRuleSet.status}
                        disabled
                      >
                        {complianceStatusOptions.map((status) => (
                          <option key={status} value={status}>
                            {status}
                          </option>
                        ))}
                      </Select>
                    </div>

                    <section className="space-y-3">
                      <div className="flex items-center justify-between gap-2">
                        <h4 className="text-sm font-semibold text-foreground">
                          Rules ({Math.max(defaultComplianceRuleSet.rules.length, 1)})
                        </h4>
                        <Button
                          type="button"
                          size="sm"
                          variant="accent"
                          className="h-8 gap-1.5 shadow-none"
                          onClick={() =>
                            onUpdateDefaultComplianceRuleSet((current) => ({
                              ...current,
                              rules: [
                                ...current.rules,
                                {
                                  name: "",
                                  description: "",
                                  category: "VISUAL",
                                  threshold: 95,
                                  is_active: true,
                                },
                              ],
                            }))
                          }
                        >
                          <Plus className="size-4" />
                          Add Rule
                        </Button>
                      </div>
                      <div className="space-y-2.5 overflow-y-auto h-52 no-border-scrollbar">
                        {(defaultComplianceRuleSet.rules.length > 0
                          ? defaultComplianceRuleSet.rules
                          : [fallbackRule]
                        ).map((rule, idx) => (
                          <div key={`default-rule-${idx}`} className="flex items-start gap-2.5">
                            <div className="flex h-11 shrink-0 items-center">
                              <Checkbox
                                id={`default-rule-active-${idx}`}
                                checked={rule.is_active}
                                onCheckedChange={(value: boolean | "indeterminate") =>
                                  updateRuleAtIndex(idx, { is_active: value === true })
                                }
                                className="h-5 w-5 rounded-[4px]"
                                aria-label={`Toggle rule ${idx + 1}`}
                                disabled={idx === 0}
                              />
                            </div>

                            <div className="min-w-0 flex-1 rounded-xl border border-border bg-background/40 p-3 shadow-sm">
                              <div className="space-y-2.5">
                                <Input
                                  id={`default-rule-name-${idx}`}
                                  value={rule.name}
                                  onChange={(e) =>
                                    updateRuleAtIndex(idx, { name: e.target.value })
                                  }
                                  placeholder="Rule name"
                                  className="h-10 font-medium"
                                  aria-label={`Rule ${idx + 1} name`}
                                />
                                <Input
                                  id={`default-rule-description-${idx}`}
                                  value={rule.description}
                                  onChange={(e) =>
                                    updateRuleAtIndex(idx, { description: e.target.value })
                                  }
                                  placeholder="Rule description"
                                  className="h-9 text-sm"
                                  aria-label={`Rule ${idx + 1} description`}
                                />
                                <div className="flex flex-col gap-2.5 sm:flex-row sm:items-center sm:justify-between">
                                  <div className="flex flex-col gap-2.5 sm:flex-row sm:items-center">
                                    <Select
                                      id={`default-rule-category-${idx}`}
                                      value={rule.category}
                                      onChange={(e) =>
                                        updateRuleAtIndex(idx, {
                                          category: e.target.value as ComplianceRuleCategory,
                                        })
                                      }
                                      className="sm:max-w-[180px]"
                                      aria-label={`Rule ${idx + 1} category`}
                                    >
                                      {complianceRuleCategoryOptions.map((category) => (
                                        <option key={category} value={category}>
                                          {category}
                                        </option>
                                      ))}
                                    </Select>
                                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                                      <Label
                                        htmlFor={`default-rule-threshold-${idx}`}
                                        className="shrink-0 text-sm font-medium text-muted-foreground"
                                      >
                                        Threshold:
                                      </Label>
                                      <Input
                                        id={`default-rule-threshold-${idx}`}
                                        type="number"
                                        step="0.01"
                                        value={String(rule.threshold)}
                                        onChange={(e) =>
                                          updateRuleAtIndex(idx, {
                                            threshold: Number(e.target.value) || 0,
                                          })
                                        }
                                        className="h-8 w-full sm:w-24"
                                        aria-label={`Rule ${idx + 1} threshold`}
                                      />
                                    </div>
                                  </div>
                                  <Button
                                    type="button"
                                    variant="ghost"
                                    size="icon-sm"
                                    className="h-8 w-8 shrink-0 text-muted-foreground hover:bg-muted hover:text-foreground"
                                    onClick={() => removeRuleAtIndex(idx)}
                                    disabled={idx === 0 || defaultComplianceRuleSet.rules.length <= 1}
                                    aria-label={`Remove rule ${idx + 1}`}
                                  >
                                    <Trash2 className="size-4" />
                                  </Button>
                                </div>
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </section>
                  </div>
                </div>
              </section>
            )}

            {activeConfigSection === "dimensions" && (
              <StoreOnboardingDimensionSection
                dimensionUnits={dimensionUnits}
                configForm={configForm}
                setConfigForm={setConfigForm}
              />
            )}
          </div>
        </div>

      </CardContent>
      <ShelfTemplateModal
        isOpen={showAddTemplateForm}
        onClose={() => {
          setShowAddTemplateForm(false);
          setEditingTemplateIndex(null);
        }}
        onSave={saveShelfTemplateFromModal}
        mode={editingTemplateIndex !== null ? "edit" : "create"}
        initialValues={newTemplate}
        extraFixtureTypeOptions={shelfFixtureLabels}
        fixtureDepthByType={Object.fromEntries(
          fixtureTypes.map((fixture) => [fixture.type, fixture.depth]),
        )}
        fixtureUnitByType={Object.fromEntries(
          fixtureTypes.map((fixture) => [fixture.type, fixture.dimension_unit]),
        )}
      />
      <StoreFixtureModal
        isOpen={fixtureModalOpen}
        onClose={() => {
          setFixtureModalOpen(false);
          setEditingFixtureIndex(null);
        }}
        onSave={saveFixtureFromModal}
        mode={editingFixtureIndex !== null ? "edit" : "create"}
        initialValues={fixtureModalInitialValues}
      />
    </Card>
  );
}

