/**
 * Mock data for Image Comparison tab.
 * Replace with API when backend is ready.
 */

import type { ImageComparisonData } from "./image-comparison-types";

export const MOCK_IMAGE_COMPARISON: ImageComparisonData = {
  planogramShelves: [
    {
      shelfName: "Shelf 1",
      shelfLabel: "Top Shelf - Snacks",
      units: 18,
      slots: [
        {
          id: "s1-p1",
          productName: "Potato Chips",
          shortName: "Potato",
          expectedFacings: 4,
          detectedFacings: 4,
          depth: 3,
          totalExpectedUnits: 12,
          totalDetectedUnits: 12,
          status: "matched",
          shape: "bag",
          color: "yellow",
        },
        {
          id: "s1-p2",
          productName: "Tortilla Chips",
          shortName: "Tortilla",
          expectedFacings: 2,
          detectedFacings: 2,
          depth: 3,
          totalExpectedUnits: 6,
          totalDetectedUnits: 6,
          status: "matched",
          shape: "bag",
          color: "yellow",
        },
      ],
    },
    {
      shelfName: "Shelf 2",
      shelfLabel: "Second Shelf - Beverages & Snacks",
      units: 45,
      slots: [
        {
          id: "s2-p1",
          productName: "Coca-Cola 500ml",
          shortName: "Coca-Cola",
          expectedFacings: 6,
          detectedFacings: 0,
          depth: 3,
          totalExpectedUnits: 18,
          totalDetectedUnits: 0,
          status: "missing",
          severity: "HIGH",
          shape: "can",
          color: "red",
        },
        {
          id: "s2-p2",
          productName: "Water Bottle 1L",
          shortName: "Water B",
          expectedFacings: 3,
          detectedFacings: 0,
          depth: 3,
          totalExpectedUnits: 9,
          totalDetectedUnits: 0,
          status: "missing",
          severity: "HIGH",
          shape: "bottle",
          color: "blue",
        },
        {
          id: "s2-p3",
          productName: "Energy Drink",
          shortName: "Energy",
          expectedFacings: 6,
          detectedFacings: 0,
          depth: 3,
          totalExpectedUnits: 18,
          totalDetectedUnits: 0,
          status: "missing",
          severity: "HIGH",
          shape: "can",
          color: "green",
        },
      ],
    },
    {
      shelfName: "Shelf 3",
      shelfLabel: "Third Shelf - Juices & Drinks",
      units: 33,
      slots: [
        {
          id: "s3-p1",
          productName: "Orange Juice 1L",
          shortName: "Orange",
          expectedFacings: 4,
          detectedFacings: 0,
          depth: 3,
          totalExpectedUnits: 12,
          totalDetectedUnits: 0,
          status: "missing",
          severity: "HIGH",
          shape: "bottle",
          color: "orange",
        },
        {
          id: "s3-p2",
          productName: "Sports Drink",
          shortName: "Sports",
          expectedFacings: 4,
          detectedFacings: 0,
          depth: 3,
          totalExpectedUnits: 12,
          totalDetectedUnits: 0,
          status: "missing",
          severity: "HIGH",
          shape: "bottle",
          color: "blue",
        },
        {
          id: "s3-p3",
          productName: "Iced Tea 500ml",
          shortName: "Iced Tea",
          expectedFacings: 3,
          detectedFacings: 0,
          depth: 3,
          totalExpectedUnits: 9,
          totalDetectedUnits: 0,
          status: "missing",
          severity: "HIGH",
          shape: "bottle",
          color: "amber",
        },
      ],
    },
    {
      shelfName: "Shelf 4",
      shelfLabel: "Bottom Shelf - Bulk Beverages",
      units: 27,
      slots: [
        {
          id: "s4-p1",
          productName: "Mineral Water 1L",
          shortName: "Mineral",
          expectedFacings: 3,
          detectedFacings: 0,
          depth: 3,
          totalExpectedUnits: 9,
          totalDetectedUnits: 0,
          status: "missing",
          severity: "HIGH",
          shape: "bottle",
          color: "slate",
        },
        {
          id: "s4-p2",
          productName: "Soft Drink 2L",
          shortName: "Soft Drink",
          expectedFacings: 3,
          detectedFacings: 0,
          depth: 3,
          totalExpectedUnits: 9,
          totalDetectedUnits: 0,
          status: "missing",
          severity: "HIGH",
          shape: "bottle",
          color: "red",
        },
        {
          id: "s4-p3",
          productName: "Pretzels",
          shortName: "Pretzels",
          expectedFacings: 2,
          detectedFacings: 2,
          depth: 3,
          totalExpectedUnits: 6,
          totalDetectedUnits: 4,
          status: "misplaced",
          severity: "MEDIUM",
          highDemand: true,
          shape: "bag",
          color: "yellow",
        },
      ],
    },
  ],
  detectionOverlays: [
    { id: "d1", label: "Green", xPercent: 5, yPercent: 8, widthPercent: 12, heightPercent: 18, status: "compliant", shelfIndex: 1 },
    { id: "d2", label: "Beige", xPercent: 18, yPercent: 8, widthPercent: 11, heightPercent: 17, status: "compliant", shelfIndex: 1 },
    { id: "d3", label: "Red Pasta Stack", xPercent: 32, yPercent: 22, widthPercent: 15, heightPercent: 20, status: "extra", shelfIndex: 4, tooltip: "Unexpected product 'Red Pasta Stack' detected on shelf 4" },
    { id: "d4", label: "Blue Pasta", xPercent: 48, yPercent: 22, widthPercent: 14, heightPercent: 19, status: "extra", shelfIndex: 4 },
    { id: "d5", label: "Black", xPercent: 65, yPercent: 25, widthPercent: 18, heightPercent: 22, status: "missing", shelfIndex: 3, tooltip: "Expected product not found at this location" },
    { id: "d6", label: "Green P", xPercent: 8, yPercent: 45, widthPercent: 10, heightPercent: 16, status: "compliant", shelfIndex: 2 },
    { id: "d7", label: "Orange", xPercent: 22, yPercent: 48, widthPercent: 12, heightPercent: 18, status: "misplaced", shelfIndex: 2, tooltip: "Product 'Orange' detected in wrong position" },
  ],
};
