import { MOCK_REPORT_SNIPPET } from "./mock-report-snippets";
import type { ReportSnippet } from "./report-snippet-types";

interface DiffIssue {
  type?: string;
  detail?: string;
  row?: number | null;
  name?: string | null;
  shelf_name?: string | null;
}

const DEFAULT_REPORT_SNIPPET: ReportSnippet = {
  ...MOCK_REPORT_SNIPPET,
  executiveSummary:
    "Analysis completed. Detailed result mapping is unavailable for this job payload.",
  keyFindings: [],
  aiRecommendations: [],
  issueCategories: [],
  issuesToReview: [],
  shelfCompliance: [],
};

function parseNumericValue(value: unknown): number {
  return typeof value === "number" && Number.isFinite(value) ? value : 0;
}

export function getAnnotatedImagePreview(
  result: Record<string, unknown> | null,
  imageMimeType?: string | null,
): string | null {
  if (!result) return null;
  const imagePath = result.image_path;
  if (!imagePath) return null;
  return `${process.env.VITE_API_URL}/${imagePath}`;
}

export function mapAnalysisResultToReportSnippet(
  result: Record<string, unknown> | null,
): ReportSnippet {
  if (!result) return DEFAULT_REPORT_SNIPPET;

  const summary = (result.summary as Record<string, unknown> | undefined) ?? {};
  const compliance = (result.compliance as Record<string, unknown> | undefined) ?? {};
  const planogramDiff = (result.planogram_diff as Record<string, unknown> | undefined) ?? {};
  const rows = (result.rows as Array<Record<string, unknown>> | undefined) ?? [];
  const issuesRaw = (planogramDiff.issues as DiffIssue[] | undefined) ?? [];
  const actionItems = (planogramDiff.action_items as string[] | undefined) ?? [];
  const detected =
    parseNumericValue(planogramDiff.detected_total) ||
    parseNumericValue(summary.total) ||
    parseNumericValue(result.count);
  const expectedTotal = parseNumericValue(planogramDiff.expected_total);

  const missing = issuesRaw.filter((issue) => issue.type === "MISSING_PRODUCT").length;
  const misplaced = issuesRaw.filter((issue) => issue.type === "MISPLACED_PRODUCT").length;
  const extra = issuesRaw.filter((issue) => issue.type === "UNEXPECTED_PRODUCT").length;
  const analysisIssues = issuesRaw.length || parseNumericValue(compliance.failed);
  const matched =
    expectedTotal > 0
      ? Math.max(expectedTotal - missing - misplaced, 0)
      : parseNumericValue(compliance.passed);
  const complianceScore = Math.max(
    0,
    Math.min(
      100,
      Math.round(
        parseNumericValue(compliance.score) ||
          parseNumericValue(planogramDiff.compliance_pct) ||
          parseNumericValue(summary.compliance_score),
      ),
    ),
  );

  const shelfCompliance = rows.map((row, index) => ({
    shelfName: `Shelf ${index + 1}`,
    compliance: complianceScore,
    units: parseNumericValue(row.count),
    skuCount: parseNumericValue(row.count),
  }));

  const issuesToReview = issuesRaw.slice(0, 6).map((issue, index) => ({
    id: `${issue.type ?? "ISSUE"}-${index}`,
    skuName: issue.name ?? undefined,
    description: issue.detail ?? "Issue detected during planogram comparison.",
    type: issue.type ?? "ANALYSIS",
    location: issue.shelf_name ?? (issue.row ? `Row ${issue.row}` : undefined),
  }));

  return {
    ...DEFAULT_REPORT_SNIPPET,
    complianceScore,
    productsDetected: detected,
    analysisIssues,
    matched,
    misplaced,
    missing,
    extra,
    issues: analysisIssues,
    facings: expectedTotal,
    units: detected,
    detected,
    gap: Math.max(expectedTotal - detected, 0),
    shelfCompliance,
    issueDistribution: { matched, misplaced, missing, extra },
    issueCategories: [
      {
        id: "missing",
        title: "Missing Products",
        count: missing,
        description: "Expected items not detected on shelf.",
        variant: "missing",
      },
      {
        id: "unexpected",
        title: "Unexpected Products",
        count: extra,
        description: "Detected items outside the expected planogram.",
        variant: "extra",
      },
      {
        id: "analysis",
        title: "Analysis Issues",
        count: analysisIssues,
        description: "Total issues generated by planogram diff rules.",
        variant: "analysis",
      },
    ],
    issuesToReview,
    executiveSummary:
      (planogramDiff.summary as string | undefined) ??
      (summary.executive_summary as string | undefined) ??
      DEFAULT_REPORT_SNIPPET.executiveSummary,
    aiRecommendations:
      actionItems.length > 0 ? actionItems : DEFAULT_REPORT_SNIPPET.aiRecommendations,
  };
}
