/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestShelvesListRouteImport } from './routes/test-shelves-list'
import { Route as TestReturnedAuditsRouteImport } from './routes/test-returned-audits'
import { Route as TestQuickStatsRouteImport } from './routes/test-quick-stats'
import { Route as TestPrimaryActionRouteImport } from './routes/test-primary-action'
import { Route as TestHeaderRouteImport } from './routes/test-header'
import { Route as TestDataLayerRouteImport } from './routes/test-data-layer'
import { Route as TestComponentsRouteImport } from './routes/test-components'
import { Route as TestCheckerHeaderRouteImport } from './routes/test-checker-header'
import { Route as TestCheckerFoundationRouteImport } from './routes/test-checker-foundation'
import { Route as TestAuditModeSelectorRouteImport } from './routes/test-audit-mode-selector'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MakerIndexRouteImport } from './routes/maker/index'
import { Route as MakerLayoutRouteImport } from './routes/maker/_layout'
import { Route as CheckerLayoutRouteImport } from './routes/checker/_layout'
import { Route as MakerAuditNewRouteImport } from './routes/maker/audit/new'

const TestShelvesListRoute = TestShelvesListRouteImport.update({
  id: '/test-shelves-list',
  path: '/test-shelves-list',
  getParentRoute: () => rootRouteImport,
} as any)
const TestReturnedAuditsRoute = TestReturnedAuditsRouteImport.update({
  id: '/test-returned-audits',
  path: '/test-returned-audits',
  getParentRoute: () => rootRouteImport,
} as any)
const TestQuickStatsRoute = TestQuickStatsRouteImport.update({
  id: '/test-quick-stats',
  path: '/test-quick-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TestPrimaryActionRoute = TestPrimaryActionRouteImport.update({
  id: '/test-primary-action',
  path: '/test-primary-action',
  getParentRoute: () => rootRouteImport,
} as any)
const TestHeaderRoute = TestHeaderRouteImport.update({
  id: '/test-header',
  path: '/test-header',
  getParentRoute: () => rootRouteImport,
} as any)
const TestDataLayerRoute = TestDataLayerRouteImport.update({
  id: '/test-data-layer',
  path: '/test-data-layer',
  getParentRoute: () => rootRouteImport,
} as any)
const TestComponentsRoute = TestComponentsRouteImport.update({
  id: '/test-components',
  path: '/test-components',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCheckerHeaderRoute = TestCheckerHeaderRouteImport.update({
  id: '/test-checker-header',
  path: '/test-checker-header',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCheckerFoundationRoute = TestCheckerFoundationRouteImport.update({
  id: '/test-checker-foundation',
  path: '/test-checker-foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAuditModeSelectorRoute = TestAuditModeSelectorRouteImport.update({
  id: '/test-audit-mode-selector',
  path: '/test-audit-mode-selector',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MakerIndexRoute = MakerIndexRouteImport.update({
  id: '/maker/',
  path: '/maker/',
  getParentRoute: () => rootRouteImport,
} as any)
const MakerLayoutRoute = MakerLayoutRouteImport.update({
  id: '/maker/_layout',
  path: '/maker',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckerLayoutRoute = CheckerLayoutRouteImport.update({
  id: '/checker/_layout',
  path: '/checker',
  getParentRoute: () => rootRouteImport,
} as any)
const MakerAuditNewRoute = MakerAuditNewRouteImport.update({
  id: '/maker/audit/new',
  path: '/maker/audit/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-audit-mode-selector': typeof TestAuditModeSelectorRoute
  '/test-checker-foundation': typeof TestCheckerFoundationRoute
  '/test-checker-header': typeof TestCheckerHeaderRoute
  '/test-components': typeof TestComponentsRoute
  '/test-data-layer': typeof TestDataLayerRoute
  '/test-header': typeof TestHeaderRoute
  '/test-primary-action': typeof TestPrimaryActionRoute
  '/test-quick-stats': typeof TestQuickStatsRoute
  '/test-returned-audits': typeof TestReturnedAuditsRoute
  '/test-shelves-list': typeof TestShelvesListRoute
  '/checker': typeof CheckerLayoutRoute
  '/maker': typeof MakerLayoutRoute
  '/maker/': typeof MakerIndexRoute
  '/maker/audit/new': typeof MakerAuditNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-audit-mode-selector': typeof TestAuditModeSelectorRoute
  '/test-checker-foundation': typeof TestCheckerFoundationRoute
  '/test-checker-header': typeof TestCheckerHeaderRoute
  '/test-components': typeof TestComponentsRoute
  '/test-data-layer': typeof TestDataLayerRoute
  '/test-header': typeof TestHeaderRoute
  '/test-primary-action': typeof TestPrimaryActionRoute
  '/test-quick-stats': typeof TestQuickStatsRoute
  '/test-returned-audits': typeof TestReturnedAuditsRoute
  '/test-shelves-list': typeof TestShelvesListRoute
  '/checker': typeof CheckerLayoutRoute
  '/maker': typeof MakerIndexRoute
  '/maker/audit/new': typeof MakerAuditNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test-audit-mode-selector': typeof TestAuditModeSelectorRoute
  '/test-checker-foundation': typeof TestCheckerFoundationRoute
  '/test-checker-header': typeof TestCheckerHeaderRoute
  '/test-components': typeof TestComponentsRoute
  '/test-data-layer': typeof TestDataLayerRoute
  '/test-header': typeof TestHeaderRoute
  '/test-primary-action': typeof TestPrimaryActionRoute
  '/test-quick-stats': typeof TestQuickStatsRoute
  '/test-returned-audits': typeof TestReturnedAuditsRoute
  '/test-shelves-list': typeof TestShelvesListRoute
  '/checker/_layout': typeof CheckerLayoutRoute
  '/maker/_layout': typeof MakerLayoutRoute
  '/maker/': typeof MakerIndexRoute
  '/maker/audit/new': typeof MakerAuditNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test-audit-mode-selector'
    | '/test-checker-foundation'
    | '/test-checker-header'
    | '/test-components'
    | '/test-data-layer'
    | '/test-header'
    | '/test-primary-action'
    | '/test-quick-stats'
    | '/test-returned-audits'
    | '/test-shelves-list'
    | '/checker'
    | '/maker'
    | '/maker/'
    | '/maker/audit/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test-audit-mode-selector'
    | '/test-checker-foundation'
    | '/test-checker-header'
    | '/test-components'
    | '/test-data-layer'
    | '/test-header'
    | '/test-primary-action'
    | '/test-quick-stats'
    | '/test-returned-audits'
    | '/test-shelves-list'
    | '/checker'
    | '/maker'
    | '/maker/audit/new'
  id:
    | '__root__'
    | '/'
    | '/test-audit-mode-selector'
    | '/test-checker-foundation'
    | '/test-checker-header'
    | '/test-components'
    | '/test-data-layer'
    | '/test-header'
    | '/test-primary-action'
    | '/test-quick-stats'
    | '/test-returned-audits'
    | '/test-shelves-list'
    | '/checker/_layout'
    | '/maker/_layout'
    | '/maker/'
    | '/maker/audit/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestAuditModeSelectorRoute: typeof TestAuditModeSelectorRoute
  TestCheckerFoundationRoute: typeof TestCheckerFoundationRoute
  TestCheckerHeaderRoute: typeof TestCheckerHeaderRoute
  TestComponentsRoute: typeof TestComponentsRoute
  TestDataLayerRoute: typeof TestDataLayerRoute
  TestHeaderRoute: typeof TestHeaderRoute
  TestPrimaryActionRoute: typeof TestPrimaryActionRoute
  TestQuickStatsRoute: typeof TestQuickStatsRoute
  TestReturnedAuditsRoute: typeof TestReturnedAuditsRoute
  TestShelvesListRoute: typeof TestShelvesListRoute
  CheckerLayoutRoute: typeof CheckerLayoutRoute
  MakerLayoutRoute: typeof MakerLayoutRoute
  MakerIndexRoute: typeof MakerIndexRoute
  MakerAuditNewRoute: typeof MakerAuditNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-shelves-list': {
      id: '/test-shelves-list'
      path: '/test-shelves-list'
      fullPath: '/test-shelves-list'
      preLoaderRoute: typeof TestShelvesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-returned-audits': {
      id: '/test-returned-audits'
      path: '/test-returned-audits'
      fullPath: '/test-returned-audits'
      preLoaderRoute: typeof TestReturnedAuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-quick-stats': {
      id: '/test-quick-stats'
      path: '/test-quick-stats'
      fullPath: '/test-quick-stats'
      preLoaderRoute: typeof TestQuickStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-primary-action': {
      id: '/test-primary-action'
      path: '/test-primary-action'
      fullPath: '/test-primary-action'
      preLoaderRoute: typeof TestPrimaryActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-header': {
      id: '/test-header'
      path: '/test-header'
      fullPath: '/test-header'
      preLoaderRoute: typeof TestHeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-data-layer': {
      id: '/test-data-layer'
      path: '/test-data-layer'
      fullPath: '/test-data-layer'
      preLoaderRoute: typeof TestDataLayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-components': {
      id: '/test-components'
      path: '/test-components'
      fullPath: '/test-components'
      preLoaderRoute: typeof TestComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-checker-header': {
      id: '/test-checker-header'
      path: '/test-checker-header'
      fullPath: '/test-checker-header'
      preLoaderRoute: typeof TestCheckerHeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-checker-foundation': {
      id: '/test-checker-foundation'
      path: '/test-checker-foundation'
      fullPath: '/test-checker-foundation'
      preLoaderRoute: typeof TestCheckerFoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-audit-mode-selector': {
      id: '/test-audit-mode-selector'
      path: '/test-audit-mode-selector'
      fullPath: '/test-audit-mode-selector'
      preLoaderRoute: typeof TestAuditModeSelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maker/': {
      id: '/maker/'
      path: '/maker'
      fullPath: '/maker/'
      preLoaderRoute: typeof MakerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maker/_layout': {
      id: '/maker/_layout'
      path: '/maker'
      fullPath: '/maker'
      preLoaderRoute: typeof MakerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checker/_layout': {
      id: '/checker/_layout'
      path: '/checker'
      fullPath: '/checker'
      preLoaderRoute: typeof CheckerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maker/audit/new': {
      id: '/maker/audit/new'
      path: '/maker/audit/new'
      fullPath: '/maker/audit/new'
      preLoaderRoute: typeof MakerAuditNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestAuditModeSelectorRoute: TestAuditModeSelectorRoute,
  TestCheckerFoundationRoute: TestCheckerFoundationRoute,
  TestCheckerHeaderRoute: TestCheckerHeaderRoute,
  TestComponentsRoute: TestComponentsRoute,
  TestDataLayerRoute: TestDataLayerRoute,
  TestHeaderRoute: TestHeaderRoute,
  TestPrimaryActionRoute: TestPrimaryActionRoute,
  TestQuickStatsRoute: TestQuickStatsRoute,
  TestReturnedAuditsRoute: TestReturnedAuditsRoute,
  TestShelvesListRoute: TestShelvesListRoute,
  CheckerLayoutRoute: CheckerLayoutRoute,
  MakerLayoutRoute: MakerLayoutRoute,
  MakerIndexRoute: MakerIndexRoute,
  MakerAuditNewRoute: MakerAuditNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
